### ISSUE TITLE
piano roll menu chords works only once

### ISSUE THREAD

**Issue by vlrprbttst** [Inversil/LESwin#1]
here's what i did:
- i changed the hotkey for the piano roll notes generation to "1".
- i chose chords > some chords in the piano roll menu
- i press "1" a click and i get a chord
- i try again with another note, nothing happens. i have to reopen the piano roll menu, reselect the chord i want and then click

basically it works only once. is there a way to not let this happen? thanks

**Comment by vlrprbttst** [comment]
im on windows using les 1.3

**Comment by Inversil** [comment]
You can keep the stamp stored by holding shift while placing it. 
Please consult this page in the LES documentation for more information about the piano menu.
https://docs.enhancementsuite.me/shortcut_menus.html#piano-menu
