### ISSUE TITLE
Bug: LES 1.3 breaks number 1-5 input in VSTs not included in VST shortcut suite when VST shortcut keys are enabled

### ISSUE THREAD

**Issue by bitcrushing** [Inversil/LESwin#10]
LES 1.3 breaks number 1-5 input in VSTs not included in VST shortcut suite when VST shortcut keys are enabled

To replicate the bug you can take the following steps:
1. Enable VST shortcuts in LES 1.3 by setting vstshortcuts=1 in the configure menu
2. Open a VST plugin which LES has no shortcuts configured for (ie. Vital, Surge, apQualizr2, etc.)
3. Open a parameter input menu in your plugin of choice and input any number 1 through 5 with the top row number keys, this should replicate the bug

I have included a screenshot of the key history after pressing numbers 1 through 5 with a pitch value input open in Surge. Setting vstshortcuts=0 allows the inputs to go through into the value field.
![keylog](https://user-images.githubusercontent.com/63355298/105503384-6a2fef00-5cbe-11eb-9022-282e4ab4f142.PNG)

Additional information if required:
OS: Windows 10
DAW: Ableton 10.1.30
LES Version: 1.3

**Comment by Inversil** [comment]
this is correct!!
I will probably remove these shortcuts in the upcoming hotfix update. I don't think anyone ever uses them. I mostly just did it to see if I could

**Comment by Inversil** [comment]
I fixed your problem in this commit! https://github.com/Inversil/LESwin/commit/209f631ba85466d542b4a6dadd8ad7b8c3c726fd
