### ISSUE TITLE
Cursor focus

### ISSUE THREAD

**Issue by hurlingpixels** [Inversil/LESwin#2]
The focus of the cursor is interrupted at times. Example: clicking away from Live to immediately adjust (click-drag) a parameter on an open 3rd party plugin. The cursor disengages despite not having let go of the mouse button. 

This only happens inside a short window of time. i.e. you can bring focus to the 3rd party plugin by clicking on it, waiting a couple seconds, then adjust parameters without issue.

**Comment by Inversil** [comment]
I can't seem to be able to recreate your issue, what version of live are you on?

**Comment by hurlingpixels** [comment]
Live 10.1.9 on Windows 10.

**Comment by ozycar** [comment]
I'm also having trouble with cursor focus in Live 10.1.9 on Windows 10, I do not know if you want a seperate issue opening?
I have this issue with plugin windows but also in projects with none present; the cursor locks to Live and mouse focus cannot be shifted until a set of conditions I cannot figure out are met. Alt-tabbing into other applications does not shift mouse focus, and sometimes force closing LES using task manager does not resolve the issue so I have to restart using keyboard inputs. It happens at seemingly random intervals, from 20 minutes into a session up to 3 hours, and only when LES is open.

**Comment by stekkko** [comment]
Same problem. Sometimes I need to restart my computer to continue my workflow :(

**Comment by christianmalek** [comment]
@stekkko What I do when this happens is pressing `Ctrl Alt Del` to open the task manager menu and then press `Cancel`. This works everytime, but for sure is annoying.

@ozycar I think it mainly happens when opening VST windows.

**Comment by Inversil** [comment]
ah yeah, the mouse focus problem; I've been experiencing this issue as well and I've been trying to fix it for about a year now. It seems some quirk in AHK is causing buttons to get stuck; things like middle click or right/left control. 

Please let me know if you figure out why it's happening, because I couldn't; sorry about that :-(

**Comment by Inversil** [comment]
I think the problem may have finally been fixed in commit this commit! https://github.com/Inversil/LESwin/commit/209f631ba85466d542b4a6dadd8ad7b8c3c726fd

Please try it the latest binary included in the repository let me know if it alleviates your issue @ozycar @stekkko @christianmalek
thank you!!

**Comment by hurlingpixels** [comment]
> I think the problem may have finally been fixed in commit this commit! [209f631](https://github.com/Inversil/LESwin/commit/209f631ba85466d542b4a6dadd8ad7b8c3c726fd)
> 
> Please try it the latest binary included in the repository let me know if it alleviates your issue @ozycar @stekkko @christianmalek
> thank you!!

This does, indeed, appear to have resolved the issue. Many thanks.
