### ISSUE TITLE
Live 11: Alt + X groups + deletes track instead of deleting clips

### ISSUE THREAD

**Issue by enoversum** [Inversil/LESwin#6]
In Live 11 (Beta), the LES shortcut Alt + X doesn't delete clips on a track, but instead creates a group around the currently selected track and then deletes both immediately. Maybe due to changed shortcuts in Live 11?

**Comment by bmason12149** [comment]
It looks like the right click menu is a bit different so I updated how this hotkey works to fix it in Ableton 11. It should also work a little more consistently (i.e. within groups).

**Comment by bmason12149** [comment]
@enoversum Looks like this fix should be pushed up to the website in the next few days so keep an eye out for that (or you can just run the most recent code from the master branch as that has the fix in it).

**Comment by enoversum** [comment]
@bmason12149 Hey there, thanks a lot for providing the fix. And yeah, hoping for this to be compiled; I'm not sure how I would do it myself :) .

**Comment by enoversum** [comment]
> 
> 
> @enoversum Looks like this fix should be pushed up to the website in the next few days so keep an eye out for that (or you can just run the most recent code from the master branch as that has the fix in it).

Well, following their announcement to quit the LES wagon, there hasn't been any updates of any kinds. I downloaded the source here (obviously with the fix), installed Auto Hotkey and compiled the script from the proper start menu command and got an .exe file out of it. The command still doesn't work and does the same or similar strange behaviour with deleting tracks. Did it work for you, @bmason12149 ?

**Comment by Inversil** [comment]
This issue was fixed in the latest commit https://github.com/Inversil/LESwin/commit/209f631ba85466d542b4a6dadd8ad7b8c3c726fd !

thank you for notifying me about this :-)
